[package]
name = "ega"
version = "0.0.0"
edition = "2021"

[dependencies]
libm = { version = "0.2.0", optional = true }
approx = { version = "0.5", optional = true }

[features]
default = ["std", "approx"]
std = []
